Algoritmo "Aprovado ou Reprovado"

Var
   Count:Inteiro
   Aluno:Alfanumerico
   Nota_1:Inteiro
   Nota_2:Inteiro
   Media:Inteiro
Inicio
      Count=0
      Enquanto Count<=4 faca
           Digite "Aluno"
           Digite "Nota_1"
           Digite "Nota_2"
           Media=(Nota_1+Nota_2)
            Se Media>=35
              Motrar "Aprovado"
            Senao
              Mostar "Reprovado"
            Count=Count++
      Fim Equanto
  Fim



Fimalgoritmo